"""empty message

Revision ID: 37b1bc01495f
Revises: 13ff5af4ac17
Create Date: 2024-03-19 13:01:27.428717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b1bc01495f'
down_revision = '13ff5af4ac17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('emailaddress', sa.String(length=70), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('date_written', sa.DateTime(), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog') as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_foreign_key('blog_user_fk', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('author_id')
        batch_op.drop_column('comments_number')
        batch_op.drop_column('likes')

    op.drop_table('comment')
    op.drop_table('user')
    # ### end Alembic commands ###
