"""empty message

Revision ID: 3b3e6bb9ad98
Revises: 0ef5da0d34c0
Create Date: 2024-04-20 00:33:58.564155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3e6bb9ad98'
down_revision = '0ef5da0d34c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('recipesInvolved', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('steps', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('conclusion', sa.Text(), nullable=False))
        batch_op.drop_column('post')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.TEXT(), nullable=False))
        batch_op.drop_column('conclusion')
        batch_op.drop_column('steps')
        batch_op.drop_column('recipesInvolved')
        batch_op.drop_column('introduction')

    # ### end Alembic commands ###
