"""empty message

Revision ID: bcf5d301b720
Revises: 58eec93694a3
Create Date: 2024-04-22 11:17:12.092265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf5d301b720'
down_revision = '58eec93694a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
